fig = figure(1);
set(fig, 'Position', [ 20 100 1400 700 ])

frame                   = uicontrol('style', 'frame', 'position',...
                            [15 582 311 110]);
text_ueberschrift       = uicontrol('style', 'text', 'string',...
                            'Enter search parameters:', 'position',...
                            [20 672 130 15]);


text_person             = uicontrol('style', 'text', 'string',...
                            'Person:', 'position', [20 652 80 15]);
search_person           = uicontrol('style', 'edit', 'position',...
                            [120 648 200 20]);

text_sentence           = uicontrol('style', 'text', 'string',...
                            'Sentence:', 'position', [20 632 80 15]);
search_sentence         = uicontrol('style', 'edit', 'position',...
                            [120 628 200 20]);

text_word               = uicontrol('style', 'text', 'string',...
                            'Word:', 'position', [20 612 80 15]);
search_word             = uicontrol('style', 'edit', 'position',...
                            [120 608 200 20]);

text_phonem             = uicontrol('style', 'text', 'string',...
                            'Phonem:', 'position', [20 592 80 15]);
search_phonem           = uicontrol('style', 'edit', 'position',...
                            [120 588 200 20]);
                        
                        %get(handles.search_person,'String')
                        
button_search           = uicontrol('style', 'pushbutton', 'string',...
                            'Search', 'position', [15 555 311 25],...
                            'callback', {@PersonSearch, search_person,...
                            @SentenceSearch, search_sentence,...
                            @WordSearch, search_word,...
                            @PhonemSearch, search_phonem});
                        
%textzeileneingabe = get(handles.search_person, 'String')